# Generated by Django 5.1 on 2024-08-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayadiapp', '0002_transaction_transaction_id_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Failed', 'Failed'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Request_sent', 'Request_sent'), ('Request_settled', 'Request settled'), ('Request_processing', 'Request processing')], default='pending', max_length=100),
        ),
    ]
