# Generated by Django 5.1 on 2024-08-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayadiapp', '0003_alter_transaction_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='numero_donneur',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='code_commercant',
            new_name='code_abonnement',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='name',
            new_name='moyen_paiement',
        ),
        migrations.AddField(
            model_name='wallet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='wallet_images/'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='type',
            field=models.CharField(default='wallet', max_length=100),
        ),
    ]
