# Generated by Django 5.1 on 2024-08-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayadiapp', '0006_remove_transaction_phone_wallet_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='code_abonnement',
            field=models.CharField(default='70abcfa8-2fb3-4741-af99-1304d8ea876b', max_length=100),
        ),
    ]
