# Generated by Django 4.2.3 on 2024-08-20 10:38

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('ayadiapp', '0008_remove_wallet_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='date_paiement',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='id_transaction',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, blank=True, length=15, max_length=20, null=True, prefix='TRN', unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='id_facture',
            field=models.CharField(blank=True, default='', editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayadiapp.wallet'),
        ),
    ]
