# Generated by Django 4.2.3 on 2024-08-29 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ayadiapp', '0009_remove_transaction_transaction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_facture', models.CharField(blank=True, default='', editable=False, max_length=20, null=True, unique=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('telephone_commercant', models.CharField(blank=True, editable=False, max_length=20, null=True)),
                ('numero_recu', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('note', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date_paiement',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='id_facture',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='remarque',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('Failed', 'Failed'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Processing', 'Processing')], default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ayadiapp.facture'),
        ),
    ]
