# Generated by Django 4.2.3 on 2024-08-29 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayadiapp', '0010_facture_remove_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='id_facture',
            field=models.CharField(blank=True, default='', max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='note',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numero_recu',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='telephone_commercant',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
