# Generated by Django 4.2.3 on 2024-08-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayadiapp', '0012_remove_transaction_code_paiement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id_transaction',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
